apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: cbci build actions
inputs:
  tosca_cloud_base_url:
    description: 'tosca public REST-API url'
    required: true
    default: ''
  tosca_auth_url:
    description: 'tosca auth url'
    required: true
    default: ''
  client_id:
    description: 'tosca cloud api client id'
    required: true
    default: ''
  client_secret:
    description: 'tosca cloud api client secret'
    required: true
    default: ''
  playlist_name:
    description: 'playlist name to be executed'
    required: true
    default: ''
  workspace:
    description: 'workspace name'
    required: true
    default: ''
  filename:
    description: 'filename'
    required: true
    default: ''
  
runs:
  using: composite
  steps:
    - id: invoke-tosca-actions
      name: invoke-tosca-actions
      uses: docker://public.ecr.aws/l7o7z1g8/actions/tosca-actions:main-170ec4a892ab202266a30a2345d3c428855fe488
      shell: sh
      run: |
        set -x
        cd /app
        ./tosca_actions_app invoke -v '{"MetaInfo":{"ToscaCloudBaseURL":"${{ inputs.tosca_cloud_base_url }}","ToscaAuthURL":"${{inputs.tosca_auth_url}}","ClientID":"${{secrets.TOSCA_CLIENT_ID}}","ClientSecret":"${{secrets.TOSCA_CLIENT_SECRET}}","PlaylistName":"${{ inputs.playlist_name }}","Workspace":"${{ inputs.workspace }}","FileName":"${{ inputs.filename }}"}}'
