= CloudBees action: Deploy with Tosca

Use this action to execute the Tricentis Tosca cloud playlist, a software testing tool that automates end-to-end testing for software applications.

[NOTE]
====
You must use the link:https://github.com/cloudbees-io/publish-test-results[Publish test results] action to populate the *Test Insights* dashboard with Tosca testing results.
====

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `tosca_cloud_base_url`
| String
| Yes
| The Tosca cloud URL.

| `tosca_auth_url`
| String
| Yes
| The URL of the authorization server (available in the Swagger UI).

| `client_id`
| String
| Yes
| The Tosca cloud API client ID.

| `client_secret`
| String
| Yes
| The Tosca cloud API token.

| `playlist_name`
| String
| Yes
| The name of the playlist to be executed.

| `workspace`
| String
| Yes
| The name of the workspace.

|===

== Usage example

[source,yaml]
----
      - name: Test with Tosca
        uses: cloudbees-io/tosca-run-job@v1
        with:
          tosca_cloud_base_url: "https://your-company.my.tricentis.com/"
          tosca_auth_url: "https://your-company.okta.com/oauth2/default/v1/token"
          client_id: ${{ secrets.TOSCA_CLIENT_ID }}
          client_secret: ${{ secrets.TOSCA_CLIENT_SECRET }}
          playlist_name: "sample playlist"
          workspace: "sample workspace"
----


== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].
